add deploy

diff --git a/.github/workflows/deploy-dev.yaml b/.github/workflows/deploy-dev.yaml
--- a/.github/workflows/deploy-dev.yaml
+++ b/.github/workflows/deploy-dev.yaml
@@ -1,11 +1,26 @@
-name: Yolo Dev Deploy
+name: Polybot Deploy Dev
 
 on:
-  push:
-    branches:
-      - dev
+  workflow_call:
+    inputs:
+      image:
+        required: true
+        type: string
+    secrets:
+      SSH_PRIVATE_KEY:
+        required: true
+      EC2_DEV_HOST:
+        required: true
+      EC2_USERNAME:
+        required: true
+      AWS_S3_BUCKET_DEV:
+        required: true
 
   workflow_dispatch:
+    inputs:
+      image:
+        required: true
+        type: string
 
 env:
   REPO_URL: ${{ github.server_url }}/${{ github.repository }}.git
@@ -24,6 +39,8 @@ jobs:
           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
           EC2_HOST: ${{ secrets.EC2_DEV_HOST }}
           EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
+          AWS_S3_BUCKET_DEV: ${{secrets.AWS_S3_BUCKET_DEV}}
+
         run: |
           mkdir -p ~/.ssh
           echo "$SSH_PRIVATE_KEY" > ~/.ssh/private_key
@@ -35,18 +52,47 @@ jobs:
               IdentityFile ~/.ssh/private_key
               StrictHostKeyChecking no
           EOF
-      - name: Copy and checkout PR branch to EC2
-#test
-        run: |
-          # Clone repository if it doesn't exist, otherwise pull latest changes
-           ssh ec2 "
-            if [ -d ~/${REPO_NAME} ]; then
-              cd ~/${REPO_NAME} && git fetch origin && git checkout dev && git pull origin dev;
-            else
-              git clone --branch dev ${REPO_URL} ~/${REPO_NAME};
-            fi
-          "
 
       - name: Execute script on EC2
         run: |
-          ssh ec2 "cd $REPO_NAME && bash deploy-dev.sh ~/${REPO_NAME} ${{secrets.AWS_S3_BUCKET_DEV}}"
+          # Generate .env file. 
+          echo "This is the image name :- ${{ inputs.image }}"
+          echo "IMG_NAME=mohammadjabaren${{ inputs.image }}" > .env
+          echo "AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET_DEV }}" >> .env
+
+          # Send .env and compose file to EC2
+          scp .env docker-compose.dev.yaml ec2:~/
+
+          # SSH into EC2 and run install + deploy
+          ssh ec2 '
+
+            sudo apt-get update
+
+            if ! command -v docker &> /dev/null; then
+              echo "Installing Docker..."
+              sudo apt-get update
+              sudo apt-get install -y ca-certificates curl
+              sudo install -m 0755 -d /etc/apt/keyrings
+              sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
+              sudo chmod a+r /etc/apt/keyrings/docker.asc
+
+              echo \
+                "deb [arch=\$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
+                \$(. /etc/os-release && echo \${UBUNTU_CODENAME:-\$VERSION_CODENAME}) stable" | \
+                sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
+
+              sudo apt-get update
+              sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
+            else
+              echo "Docker already installed."
+            fi
+
+            if ! command -v docker &> /dev/null; then
+              echo "Docker installation failed or not found. Exiting."
+              exit 1
+            fi
+
+            echo "Starting Docker Compose services..."
+            sudo docker compose -f docker-compose.dev.yaml pull
+            sudo docker compose -f docker-compose.dev.yaml up -d
+          '
